version: '3.7'
services:
  redpanda1:
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: redpanda1
    command:
    - redpanda
    - start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 0
    - --check=false
    - --pandaproxy-addr INSIDE://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr INSIDE://redpanda1:28082,OUTSIDE://localhost:8082
    - --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr INSIDE://redpanda1:29092,OUTSIDE://localhost:9092
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda1:33145
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 9644:9644
    networks:
      - redpanda-network
  redpanda2:
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: redpanda2
    command:
    - redpanda
    - start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 1
    - --seeds "redpanda1:33145"
    - --check=false
    - --pandaproxy-addr INSIDE://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
    - --advertise-pandaproxy-addr INSIDE://redpanda2:28083,OUTSIDE://localhost:8083
    - --kafka-addr INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
    - --advertise-kafka-addr INSIDE://redpanda2:29093,OUTSIDE://localhost:9093
    - --rpc-addr 0.0.0.0:33146
    - --advertise-rpc-addr redpanda2:33146
    depends_on:
      - redpanda-1
    ports:
    - 8083:8083
    - 9093:9093
    networks:
      - redpanda-network
  redpanda3:
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: redpanda3
    command:
    - redpanda
    - start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 2
    - --seeds "redpanda1:33145"
    - --check=false
    - --pandaproxy-addr INSIDE://0.0.0.0:28084,OUTSIDE://0.0.0.0:8084
    - --advertise-pandaproxy-addr INSIDE://redpanda3:28084,OUTSIDE://localhost:8084
    - --kafka-addr INSIDE://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
    - --advertise-kafka-addr INSIDE://redpanda3:29094,OUTSIDE://localhost:9094
    - --rpc-addr 0.0.0.0:33147
    - --advertise-rpc-addr redpanda3:33147
    depends_on:
      - redpanda2
    ports:
    - 8084:8084
    - 9094:9094
    networks:
      - redpanda-network
networks:
  redpanda-network:
    driver: bridge